first:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  wheel_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: wheel_joint
    pid:
      p: 100.0
      i: 0.0
      d: 0.0
