joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

wheel_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: wheel_joint
  pid:
    p: 0.7
    i: 0.0
    d: 0.0
    i_clamp: 1000.0
