<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="first">

  <!-- Global constants -->
  <xacro:property name="pi" value="3.1415926535897931"/>

  <!-- Included files -->
  <xacro:include filename="$(find first_description)/urdf/materials.urdf.xacro"/>
  <xacro:include filename="$(find first_description)/urdf/common.urdf.xacro"/>

  <!-- Robot properties -->
  <xacro:property name="base_width" value="0.03"/>
  <xacro:property name="base_length" value="0.05"/>
  <xacro:property name="base_height" value="0.05"/>

  <xacro:property name="wheel_width" value="0.01"/>
  <xacro:property name="wheel_radius" value="0.04"/>

  <xacro:property name="wheel_holder_size" value="0.01"/>

  <link name="base_link">
    <visual>
      <xacro:box_geometry width="${base_width}" depth="${base_height}" height="${base_length}"/>
      <xacro:white_material/>
    </visual>
    <xacro:box_collision width="${base_width}" depth="${base_height}" height="${base_length}"/>
    <xacro:box_inertia mass="0.2" width="${base_width}" depth="${base_height}" height="${base_length}"/>
  </link>

  <link name="wheel_holder">
    <visual>
      <xacro:box_geometry width="${wheel_holder_size}" height="${wheel_holder_size}" depth="${wheel_holder_size}"/>
      <xacro:green_material/>
    </visual>
    <xacro:box_collision width="${wheel_holder_size}" height="${wheel_holder_size}" depth="${wheel_holder_size}"/>
    <xacro:box_inertia mass="0.003" width="${wheel_holder_size}" height="${wheel_holder_size}"
                       depth="${wheel_holder_size}"/>
  </link>

  <joint name="base_to_wheel_holder" type="fixed">
    <parent link="base_link"/>
    <child link="wheel_holder"/>
    <origin xyz="0 0 ${base_height/2 + wheel_holder_size/2}" rpy="0 0 0" />
    <axis xyz="0 0 1" />
  </joint>

  <link name="wheel">
    <visual>
      <xacro:cylinder_geometry radius="${wheel_radius}" height="${wheel_width}"/>
      <xacro:black_material/>
    </visual>
    <xacro:cylinder_collision radius="${wheel_radius}" height="${wheel_width}"/>
    <xacro:cylinder_inertia mass="0.03" radius="${wheel_radius}" height="${wheel_width}"/>
    <dynamics damping="0.01" friction="100.0" />
  </link>

  <joint name="wheel_joint" type="continuous">
    <parent link="wheel_holder"/>
    <child link="wheel"/>
    <origin xyz="0 0 ${wheel_width/2 + wheel_holder_size/2}" rpy="0 0 0" />
    <axis xyz="0 0 1" />
    <limit effort="100" velocity="100" />
    <dynamics damping="0.01" friction="100.0" />
  </joint>

  <transmission name="wheel_transmission">
     <type>transmission_interface/SimpleTransmission</type>
     <joint name="wheel_joint">
       <hardwareInterface>VelocityJointInterface</hardwareInterface>
     </joint>
     <actuator name="wheel_motor">
       <hardwareInterface>VelocityJointInterface</hardwareInterface>
       <mechanicalReduction>1</mechanicalReduction>
     </actuator>
  </transmission>

</robot>


